### ISSUE TITLE
Invalid extension name in config

### ISSUE THREAD

**Issue by FilipLukac** [lookyman/nette-texy#4]
Hello,

I've just downloaded your extension and found an issue with configuration file.

In documentation is:

```
extensions:
    texy: lookyman\NetteTexy\DI\TexyExtension
```

With lowercase L at name of the extension. I've just changed lowercase l to uppercase L.

```
extensions:
    texy: Lookyman\NetteTexy\DI\TexyExtension
```

So, just change your documentation :)

**Comment by lookyman** [comment]
Thanks!
